### ISSUE TITLE
Errors in the default template

### ISSUE THREAD

**Issue by floriancargoet** [elliotherriman/calico#11]
Congratulations on the new release!

Some issues I've encountered:
- the template zip in the release page still includes `choicetags.js` but the release says it's removed
- the project.js in the template (zip & repo) still imports `choicetags.js`
- opening the template project results in an error:
```
Uncaught (in promise) Error: Can't resolve filename because no FileHandler was provided when instantiating the parser / compiler.
```
That's because the template project uses storylets & the ink file has `INCLUDE patches/storylets.ink` which the compiler doesn't know how to load.
I suggest providing a much simpler project.js in the default template, at least not including storylets since it doesn't load correctly. 

I'm happy that Calico got a new release, now I can work on it knowing it's very much alive :-D
I found a few bugs in the v1 a few weeks ago, I haven't yet checked if they're fixed in v2. I'll report here if I find anything.
Are you open to pull requests or do you prefer issues and tackling them yourself?

**Comment by elliotherriman** [comment]
Oh damn, thanks for letting me know! I'm definitely open to pull requests, but you're more than welcome to just report bugs too.

I'll get the template issues sorted shortly. INCLUDEs are unfortunately a more complicated issue (I can't believe I didn't think to test that), but I've reached out to someone on the inkjs team to get that figured out too!
