### ISSUE TITLE
linebyline doesn't work as documented

### ISSUE THREAD

**Issue by floriancargoet** [elliotherriman/calico#12]
The code for the linebyline tag:
```
  if (typeof property === undefined) {
    story.queue.setLineByLine(!story.queue.lineByLine || true);
  }
  else {
    story.queue.setLineByLine(!!property);
  }
```

`typeof` returns a string, so you probably meant `typeof property === "undefined"`. 
As it is, the `if` will always be false and always run the `else` case.

**Comment by elliotherriman** [comment]
Oh, good eye! Thanks!
