### ISSUE TITLE
Can't create a new Story with storyContent directly

### ISSUE THREAD

**Issue by floriancargoet** [elliotherriman/calico#13]
We can't load storyContent directly since v2.

In `loadInk()`, the code in incorrect.
It first checks if `input.endsWith(".ink")` which throws an exception if it's not a string.
This check should be nested inside the ` if (typeof input === "string") {` not before.

Here the existing code for reference:
```js
loadInk(input) {
    // if we tried loading an ink file,
    if (input.endsWith(".ink")) {
      ...
    }
    // if we've been handed a string, it might be the story data, or it
    // might be a file name that we need to load
    else if (typeof input === "string") {
     ...
    }
    // otherwise, if it's already loaded as an object, we load that
    else if (input.inkVersionCurrent) {
      ...
    }
  }
  ```

**Comment by floriancargoet** [comment]
Somewhat related issue: my storyContent contains `inkVersion` not `inkVersionCurrent`. Is it a change in ink or calico ?

**Comment by elliotherriman** [comment]
Should be resolved now, thank you!
