### ISSUE TITLE
[patches/storage.js] get incorrectly returns false

### ISSUE THREAD

**Issue by floriancargoet** [elliotherriman/calico#22]
In `patches/storage.js`, if we `set()` a value of 0, `get()` will return `false`.

```
ExternalFunctions.add("get", (value) => 
	{ 
		var v = get(value);
		return (isNaN(v) ? v : parseFloat(v)) || false;
	
	});
```

`|| false` is the cause of this bug.

Also, instead of checking only for numbers, we could use JSON.stringify() for encoding and JSON.parse() for decoding. It works well to encode strings, booleans, numbers.

**Comment by floriancargoet** [comment]
Another weird thing about storage: 
 - `set` can specify the format
 - `get` can't.

**Comment by elliotherriman** [comment]
> Another weird thing about storage:
> 
> * `set` can specify the format
> * `get` can't.

Unfortunately, yes, that's correct. Ink doesn't let you declare multiple functions with the same name, so it's not possible to have both `get(id)` and `get(id, format)`. Users can change `storage_defaultformat`, or create their own external functions themselves if they want to juggle multiple formats.

Fantastic spot on this issue, though! I'll push a fix shortly.

**Comment by floriancargoet** [comment]
That's not what I meant.
You declare either get(id) or get(id, format) on the ink side but the JS function exposed is a version that only that id, whereas the exposed set() function handles all parameters. (`set` is exposed as-is while `get` has an intermediary function which only passes id)

**Comment by elliotherriman** [comment]
Ah, I see! Yep, fix coming shortly.

**Comment by floriancargoet** [comment]
Something doesn't work.
When calling set from memorycard, the `this` arg is storage so your new arg `story = this` means `story = storage`
Then storage.options.storage_ID is not the same as story.options.storage_ID.
The result is that storage_ID is "" instead of location.pathname.

**Comment by floriancargoet** [comment]
Also, storage.remove now want the story as first param whereas it was bound before. In any case, the API should be similar to get/set.

**Comment by elliotherriman** [comment]
Ugh, yep, I see how this happened. Serves me right for programming while sick. Should be fixed now!
