### ISSUE TITLE
new tag options format doesn't work

### ISSUE THREAD

**Issue by floriancargoet** [elliotherriman/calico#25]
The doc says:
> Some tags can be customised via options, which by convention are separated with a ">>". For example, in musicplayer.js, you can delay a track by using the delay option.
>```
>#play: act4 >> delay: 500
>```

This doesn't work. Nothing in the code seems to be handling that syntax and I can see the code for parsing the old format in `getTagOptions`.
Is this in some uncommited code?

**Comment by elliotherriman** [comment]
Hmm, I definitely remember committing that code... strange. Thanks for pointing that out!
