### ISSUE TITLE
[Discussion] Adding code quality tools

### ISSUE THREAD

**Issue by floriancargoet** [elliotherriman/calico#26]
What are your thoughts on adding some code quality tools to this codebase?
I'm thinking:
- `prettier` for a consistent and somewhat standard formatting
- `eslint` to prevent mistakes and follow useful conventions
- maybe `TypeScript`?

**Comment by elliotherriman** [comment]
I'm definitely open to adding `eslint`. That said, I've unfortunately had very little free time lately (work is eating eating up 90% of my waking hours) — so if this does happen, it will probably be at a much later date.

My next priority is adding unit tests. I was hoping to have this done before releasing 2.0.0, but I rushed that out in an alpha state upon request.
