### ISSUE TITLE
autosave_id option

### ISSUE THREAD

**Issue by floriancargoet** [elliotherriman/calico#28]
All games using **autosave** will have their data stored with the "save" id. 
This is a problem on Itch where all games share the same `sessionStorage`. 
**autosave** should have a `autosave_id` option that is passed to **memorycard** so authors can use a unique custom id.

**Comment by elliotherriman** [comment]
From what I remember, itch.io games shared localStorage, but not sessionStorage. That said, I'll add an ID option, that seems wise.

**Comment by floriancargoet** [comment]
Session storage is shared if:
 - same domain (which is the case for all itch iframes)
 - same session (meaning same tab)

One realistic case where it can happen:
 - you play Game A in a tab
 - then you play Game B in the **same** tab (following a link or even typing the URL by hand)
In that case, the sessionStorage is shared.
